from enum import Enum
class LogTypes(str,Enum):
    BOOK_INSERTION = 'book_insertion'
    BOOK_DELETION = 'book_deletion'
    SUSPECTED_DUPLICATE = 'suspected_duplicate'
    BOOKFIELD_AMENDED = 'bookfield_amended'
    BOOKFIELD_INSERTED = 'bookfield_inserted'
    BOOKFIELD_DELETED = 'bookfield_deleted'
    BOOK_MISSING_MANDATORY_BOOKFIELDS = 'book_missing_mandatory_bookfields'
    INSTRUMENTS_INSERTION = 'instruments_insertion'
    INSTRUMENTS_DELETION = 'instruments_deletion'
    INSTRUMENTS_AMENDED = 'instruments_amended'
    SYMBOLS_INSERTION = 'symbols_insertion'
    SYMBOLS_DELETION = 'symbols_deletion'
    SYMBOLS_AMENDED = 'symbols_amended'
    EXCHANGES_INSERTION = 'exchanges_insertion'
    EXCHANGES_DELETION = 'exchanges_deletion'
    EXCHANGES_AMENDED = 'exchanges_amended'
